/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FirmwareStatusNotificationRequestV201 {
  customData?: CustomDataType;
  status: FirmwareStatusEnumType;
  /**
   * The request id that was provided in the
   * UpdateFirmwareRequest that started this firmware update.
   * This field is mandatory, unless the message was triggered by a TriggerMessageRequest AND there is no firmware update ongoing.
   *
   */
  requestId?: number;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}

/**
 * This contains the progress status of the firmware installation.
 *
 */
export const enum FirmwareStatusEnumType {
  Downloaded = "Downloaded",
  DownloadFailed = "DownloadFailed",
  Downloading = "Downloading",
  DownloadScheduled = "DownloadScheduled",
  DownloadPaused = "DownloadPaused",
  Idle = "Idle",
  InstallationFailed = "InstallationFailed",
  Installing = "Installing",
  Installed = "Installed",
  InstallRebooting = "InstallRebooting",
  InstallScheduled = "InstallScheduled",
  InstallVerificationFailed = "InstallVerificationFailed",
  InvalidSignature = "InvalidSignature",
  SignatureVerified = "SignatureVerified"
}
