/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 5
 * @maxItems 5
 */
export type RpcCallErrorV201 = [
  MessageTypeId,
  string,
  ErrorCode,
  string,
  {
    [k: string]: unknown;
  }
];
export type MessageTypeId = 4;

export const enum ErrorCode {
  NotImplemented = "NotImplemented",
  NotSupported = "NotSupported",
  InternalError = "InternalError",
  ProtocolError = "ProtocolError",
  SecurityError = "SecurityError",
  FormationViolation = "FormationViolation",
  PropertyConstraintViolation = "PropertyConstraintViolation",
  OccurenceConstraintViolation = "OccurenceConstraintViolation",
  TypeConstraintViolation = "TypeConstraintViolation",
  GenericError = "GenericError"
}
