/**
 * Generated by scripts/schema-ast.ts */
import authorizeResponseV16 from ".//authorize-response.json";
import authorizeRequestV16 from ".//authorize.json";
import bootNotificationResponseV16 from ".//boot-notification-response.json";
import bootNotificationRequestV16 from ".//boot-notification.json";
import cancelReservationResponseV16 from ".//cancel-reservation-response.json";
import cancelReservationRequestV16 from ".//cancel-reservation.json";
import changeAvailabilityResponseV16 from ".//change-availability-response.json";
import changeAvailabilityRequestV16 from ".//change-availability.json";
import changeConfigurationResponseV16 from ".//change-configuration-response.json";
import changeConfigurationRequestV16 from ".//change-configuration.json";
import clearCacheResponseV16 from ".//clear-cache-response.json";
import clearCacheRequestV16 from ".//clear-cache.json";
import clearChargingProfileResponseV16 from ".//clear-charging-profile-response.json";
import clearChargingProfileRequestV16 from ".//clear-charging-profile.json";
import dataTransferResponseV16 from ".//data-transfer-response.json";
import dataTransferRequestV16 from ".//data-transfer.json";
import diagnosticsStatusNotificationResponseV16 from ".//diagnostics-status-notification-response.json";
import diagnosticsStatusNotificationRequestV16 from ".//diagnostics-status-notification.json";
import firmwareStatusNotificationResponseV16 from ".//firmware-status-notification-response.json";
import firmwareStatusNotificationRequestV16 from ".//firmware-status-notification.json";
import getCompositeScheduleResponseV16 from ".//get-composite-schedule-response.json";
import getCompositeScheduleRequestV16 from ".//get-composite-schedule.json";
import getConfigurationResponseV16 from ".//get-configuration-response.json";
import getConfigurationRequestV16 from ".//get-configuration.json";
import getDiagnosticsResponseV16 from ".//get-diagnostics-response.json";
import getDiagnosticsRequestV16 from ".//get-diagnostics.json";
import getLocalListVersionResponseV16 from ".//get-local-list-version-response.json";
import getLocalListVersionRequestV16 from ".//get-local-list-version.json";
import heartbeatResponseV16 from ".//heartbeat-response.json";
import heartbeatRequestV16 from ".//heartbeat.json";
import meterValuesResponseV16 from ".//meter-values-response.json";
import meterValuesRequestV16 from ".//meter-values.json";
import remoteStartTransactionResponseV16 from ".//remote-start-transaction-response.json";
import remoteStartTransactionRequestV16 from ".//remote-start-transaction.json";
import remoteStopTransactionResponseV16 from ".//remote-stop-transaction-response.json";
import remoteStopTransactionRequestV16 from ".//remote-stop-transaction.json";
import reserveNowResponseV16 from ".//reserve-now-response.json";
import reserveNowRequestV16 from ".//reserve-now.json";
import resetResponseV16 from ".//reset-response.json";
import resetRequestV16 from ".//reset.json";
import rpcCallErrorV16 from ".//rpc-call-error.json";
import rpcCallResultV16 from ".//rpc-call-result.json";
import rpcCallV16 from ".//rpc-call.json";
import sendLocalListResponseV16 from ".//send-local-list-response.json";
import sendLocalListRequestV16 from ".//send-local-list.json";
import setChargingProfileResponseV16 from ".//set-charging-profile-response.json";
import setChargingProfileRequestV16 from ".//set-charging-profile.json";
import startTransactionResponseV16 from ".//start-transaction-response.json";
import startTransactionRequestV16 from ".//start-transaction.json";
import statusNotificationResponseV16 from ".//status-notification-response.json";
import statusNotificationRequestV16 from ".//status-notification.json";
import stopTransactionResponseV16 from ".//stop-transaction-response.json";
import stopTransactionRequestV16 from ".//stop-transaction.json";
import triggerMessageResponseV16 from ".//trigger-message-response.json";
import triggerMessageRequestV16 from ".//trigger-message.json";
import unlockConnectorResponseV16 from ".//unlock-connector-response.json";
import unlockConnectorRequestV16 from ".//unlock-connector.json";
import updateFirmwareResponseV16 from ".//update-firmware-response.json";
import updateFirmwareRequestV16 from ".//update-firmware.json";

export const schemas = {
  v16: {
    authorizeResponseV16,
    authorizeRequestV16,
    bootNotificationResponseV16,
    bootNotificationRequestV16,
    cancelReservationResponseV16,
    cancelReservationRequestV16,
    changeAvailabilityResponseV16,
    changeAvailabilityRequestV16,
    changeConfigurationResponseV16,
    changeConfigurationRequestV16,
    clearCacheResponseV16,
    clearCacheRequestV16,
    clearChargingProfileResponseV16,
    clearChargingProfileRequestV16,
    dataTransferResponseV16,
    dataTransferRequestV16,
    diagnosticsStatusNotificationResponseV16,
    diagnosticsStatusNotificationRequestV16,
    firmwareStatusNotificationResponseV16,
    firmwareStatusNotificationRequestV16,
    getCompositeScheduleResponseV16,
    getCompositeScheduleRequestV16,
    getConfigurationResponseV16,
    getConfigurationRequestV16,
    getDiagnosticsResponseV16,
    getDiagnosticsRequestV16,
    getLocalListVersionResponseV16,
    getLocalListVersionRequestV16,
    heartbeatResponseV16,
    heartbeatRequestV16,
    meterValuesResponseV16,
    meterValuesRequestV16,
    remoteStartTransactionResponseV16,
    remoteStartTransactionRequestV16,
    remoteStopTransactionResponseV16,
    remoteStopTransactionRequestV16,
    reserveNowResponseV16,
    reserveNowRequestV16,
    resetResponseV16,
    resetRequestV16,
    rpcCallErrorV16,
    rpcCallResultV16,
    rpcCallV16,
    sendLocalListResponseV16,
    sendLocalListRequestV16,
    setChargingProfileResponseV16,
    setChargingProfileRequestV16,
    startTransactionResponseV16,
    startTransactionRequestV16,
    statusNotificationResponseV16,
    statusNotificationRequestV16,
    stopTransactionResponseV16,
    stopTransactionRequestV16,
    triggerMessageResponseV16,
    triggerMessageRequestV16,
    unlockConnectorResponseV16,
    unlockConnectorRequestV16,
    updateFirmwareResponseV16,
    updateFirmwareRequestV16
  }
};
