/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BootNotificationResponseV16 {
  status: BootNotificationResponseStatusEnumType;
  currentTime: string;
  interval: number;
}

export const enum BootNotificationResponseStatusEnumType {
  Accepted = "Accepted",
  Pending = "Pending",
  Rejected = "Rejected"
}
