/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StatusEnumType = "Accepted" | "Pending" | "Rejected";

export interface BootNotificationResponseV16 {
  status: StatusEnumType;
  currentTime: string;
  interval: number;
}
