/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ChangeConfigurationResponseV16 {
  status: ChangeConfigurationStatus;
}

export const enum ChangeConfigurationStatus {
  Accepted = "Accepted",
  Rejected = "Rejected",
  RebootRequired = "RebootRequired",
  NotSupported = "NotSupported"
}
