/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DataTransferResponseV16 {
  status: DataTransferStatus;
  data?: string;
}

export const enum DataTransferStatus {
  Accepted = "Accepted",
  Rejected = "Rejected",
  UnknownMessageId = "UnknownMessageId",
  UnknownVendorId = "UnknownVendorId"
}
