/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DeleteCertificateRequestV16 {
  certificateHashData: CertificateHashDataType;
}
export interface CertificateHashDataType {
  hashAlgorithm: HashAlgorithmEnumType;
  issuerNameHash: string;
  issuerKeyHash: string;
  serialNumber: string;
}

export const enum HashAlgorithmEnumType {
  SHA256 = "SHA256",
  SHA384 = "SHA384",
  SHA512 = "SHA512"
}
