/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DeleteCertificateResponseV16 {
  status: DeleteCertificateStatusEnumType;
}

export const enum DeleteCertificateStatusEnumType {
  Accepted = "Accepted",
  Failed = "Failed",
  NotFound = "NotFound"
}
