/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MessageTriggerEnumType =
  | "BootNotification"
  | "LogStatusNotification"
  | "FirmwareStatusNotification"
  | "Heartbeat"
  | "MeterValues"
  | "SignChargePointCertificate"
  | "StatusNotification";

export interface ExtendedTriggerMessageRequestV16 {
  requestedMessage: MessageTriggerEnumType;
  connectorId?: number;
}
