/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FirmwareStatusNotificationRequestV16 {
  status: FirmwareStatus;
}

export const enum FirmwareStatus {
  Downloaded = "Downloaded",
  DownloadFailed = "DownloadFailed",
  Downloading = "Downloading",
  Idle = "Idle",
  InstallationFailed = "InstallationFailed",
  Installing = "Installing",
  Installed = "Installed"
}
