/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetCompositeScheduleResponseV16 {
  status: GetCompositeScheduleStatus;
  connectorId?: number;
  scheduleStart?: string;
  chargingSchedule?: {
    duration?: number;
    startSchedule?: string;
    chargingRateUnit: ChargingRateUnit;
    chargingSchedulePeriod: {
      startPeriod: number;
      limit: number;
      numberPhases?: number;
    }[];
    minChargingRate?: number;
  };
}

export const enum GetCompositeScheduleStatus {
  Accepted = "Accepted",
  Rejected = "Rejected"
}
export const enum ChargingRateUnit {
  A = "A",
  W = "W"
}
