/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetLogResponseV16 {
  status: LogStatusEnumType;
  filename?: string;
}

export const enum LogStatusEnumType {
  Accepted = "Accepted",
  Rejected = "Rejected",
  AcceptedCanceled = "AcceptedCanceled"
}
