/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstallCertificateResponseV16 {
  status: InstallCertificateStatusEnumType;
}

export const enum InstallCertificateStatusEnumType {
  Accepted = "Accepted",
  Failed = "Failed",
  Rejected = "Rejected"
}
