/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstallCertificateRequestV16 {
  certificateType: CertificateUseEnumType;
  certificate: string;
}

export const enum CertificateUseEnumType {
  CentralSystemRootCertificate = "CentralSystemRootCertificate",
  ManufacturerRootCertificate = "ManufacturerRootCertificate"
}
