/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RemoteStartTransactionRequestV16 {
  connectorId?: number;
  idTag: string;
  chargingProfile?: {
    chargingProfileId: number;
    transactionId?: number;
    stackLevel: number;
    chargingProfilePurpose: ChargingProfilePurpose;
    chargingProfileKind?: ChargingProfileKind;
    recurrencyKind?: RecurringKind;
    validFrom?: string;
    validTo?: string;
    chargingSchedule: {
      duration?: number;
      startSchedule?: string;
      chargingRateUnit: ChargingRateUnit;
      chargingSchedulePeriod: {
        startPeriod: number;
        limit: number;
        numberPhases?: number;
      }[];
      minChargingRate?: number;
    };
  };
}

export const enum ChargingProfilePurpose {
  ChargePointMaxProfile = "ChargePointMaxProfile",
  TxDefaultProfile = "TxDefaultProfile",
  TxProfile = "TxProfile"
}
export const enum ChargingProfileKind {
  Absolute = "Absolute",
  Recurring = "Recurring",
  Relative = "Relative"
}
export const enum RecurringKind {
  Daily = "Daily",
  Weekly = "Weekly"
}
export const enum ChargingRateUnit {
  A = "A",
  W = "W"
}
