/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ResetResponseV16 {
  status: ResetStatus;
}

export const enum ResetStatus {
  Accepted = "Accepted",
  Rejected = "Rejected"
}
