/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StatusEnumType = "Accepted" | "Faulted" | "Occupied" | "Rejected" | "Unavailable";

export interface ReserveNowResponseV16 {
  status: StatusEnumType;
}
