/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 4
 * @maxItems 4
 */
export type RpcCallV16 = [
  MessageTypeId,
  string,
  Action,
  {
    [k: string]: unknown;
  }
];
export type MessageTypeId = 2;

export const enum Action {
  Authorize = "Authorize",
  BootNotification = "BootNotification",
  CancelReservation = "CancelReservation",
  CertificateSigned = "CertificateSigned",
  ChangeAvailability = "ChangeAvailability",
  ChangeConfiguration = "ChangeConfiguration",
  ClearCache = "ClearCache",
  ClearChargingProfile = "ClearChargingProfile",
  DataTransfer = "DataTransfer",
  DeleteCertificate = "DeleteCertificate",
  DiagnosticsStatusNotification = "DiagnosticsStatusNotification",
  ExtendedTriggerMessage = "ExtendedTriggerMessage",
  FirmwareStatusNotification = "FirmwareStatusNotification",
  GetCompositeSchedule = "GetCompositeSchedule",
  GetConfiguration = "GetConfiguration",
  GetDiagnostics = "GetDiagnostics",
  GetInstalledCertificateIds = "GetInstalledCertificateIds",
  GetLocalListVersion = "GetLocalListVersion",
  GetLog = "GetLog",
  Heartbeat = "Heartbeat",
  InstallCertificate = "InstallCertificate",
  LogStatusNotification = "LogStatusNotification",
  MeterValues = "MeterValues",
  RemoteStartTransaction = "RemoteStartTransaction",
  RemoteStopTransaction = "RemoteStopTransaction",
  ReserveNow = "ReserveNow",
  Reset = "Reset",
  SecurityEventNotification = "SecurityEventNotification",
  SendLocalList = "SendLocalList",
  SetChargingProfile = "SetChargingProfile",
  SignCertificate = "SignCertificate",
  SignedFirmwareStatusNotification = "SignedFirmwareStatusNotification",
  SignedUpdateFirmware = "SignedUpdateFirmware",
  StartTransaction = "StartTransaction",
  StatusNotification = "StatusNotification",
  StopTransaction = "StopTransaction",
  TriggerMessage = "TriggerMessage",
  UnlockConnector = "UnlockConnector",
  UpdateFirmware = "UpdateFirmware"
}
