/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 5
 * @maxItems 5
 */
export type RpcCallErrorV16 = [
  4,
  string,
  (
    | "NotImplemented"
    | "NotSupported"
    | "InternalError"
    | "ProtocolError"
    | "SecurityError"
    | "FormationViolation"
    | "PropertyConstraintViolation"
    | "OccurenceConstraintViolation"
    | "TypeConstraintViolation"
    | "GenericError"
  ),
  string,
  {
    [k: string]: unknown;
  }
];
