/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SendLocalListRequestV16 {
  listVersion: number;
  localAuthorizationList?: {
    idTag: string;
    idTagInfo?: {
      expiryDate?: string;
      parentIdTag?: string;
      status: AuthorizationStatus;
    };
  }[];
  updateType: UpdateType;
}

export const enum AuthorizationStatus {
  Accepted = "Accepted",
  Blocked = "Blocked",
  Expired = "Expired",
  Invalid = "Invalid",
  ConcurrentTx = "ConcurrentTx"
}
export const enum UpdateType {
  Differential = "Differential",
  Full = "Full"
}
