/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SignedFirmwareStatusNotificationRequestV16 {
  status: FirmwareStatusEnumType;
  requestId?: number;
}

export const enum FirmwareStatusEnumType {
  Downloaded = "Downloaded",
  DownloadFailed = "DownloadFailed",
  Downloading = "Downloading",
  DownloadScheduled = "DownloadScheduled",
  DownloadPaused = "DownloadPaused",
  Idle = "Idle",
  InstallationFailed = "InstallationFailed",
  Installing = "Installing",
  Installed = "Installed",
  InstallRebooting = "InstallRebooting",
  InstallScheduled = "InstallScheduled",
  InstallVerificationFailed = "InstallVerificationFailed",
  InvalidSignature = "InvalidSignature",
  SignatureVerified = "SignatureVerified"
}
