/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SignedUpdateFirmwareResponseV16 {
  status: SignedUpdateFirmwareStatus;
}

export const enum SignedUpdateFirmwareStatus {
  Accepted = "Accepted",
  Rejected = "Rejected",
  AcceptedCanceled = "AcceptedCanceled",
  InvalidCertificate = "InvalidCertificate",
  RevokedCertificate = "RevokedCertificate"
}
