/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StatusNotificationRequestV16 {
  connectorId: number;
  errorCode: ChargePointErrorCode;
  info?: string;
  status: ChargePointStatus;
  timestamp?: string;
  vendorId?: string;
  vendorErrorCode?: string;
}

export const enum ChargePointErrorCode {
  ConnectorLockFailure = "ConnectorLockFailure",
  EVCommunicationError = "EVCommunicationError",
  GroundFailure = "GroundFailure",
  HighTemperature = "HighTemperature",
  InternalError = "InternalError",
  LocalListConflict = "LocalListConflict",
  NoError = "NoError",
  OtherError = "OtherError",
  OverCurrentFailure = "OverCurrentFailure",
  PowerMeterFailure = "PowerMeterFailure",
  PowerSwitchFailure = "PowerSwitchFailure",
  ReaderFailure = "ReaderFailure",
  ResetFailure = "ResetFailure",
  UnderVoltage = "UnderVoltage",
  OverVoltage = "OverVoltage",
  WeakSignal = "WeakSignal"
}
export const enum ChargePointStatus {
  Available = "Available",
  Preparing = "Preparing",
  Charging = "Charging",
  SuspendedEV = "SuspendedEV",
  SuspendedEVSE = "SuspendedEVSE",
  Finishing = "Finishing",
  Reserved = "Reserved",
  Unavailable = "Unavailable",
  Faulted = "Faulted"
}
