/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StopTransactionResponseV16 {
  idTagInfo?: {
    expiryDate?: string;
    parentIdTag?: string;
    status: AuthorizationStatus;
  };
}

export const enum AuthorizationStatus {
  Accepted = "Accepted",
  Blocked = "Blocked",
  Expired = "Expired",
  Invalid = "Invalid",
  ConcurrentTx = "ConcurrentTx"
}
