/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TriggerMessageRequestV16 {
  requestedMessage: RequestedMessage;
  connectorId?: number;
}

export const enum RequestedMessage {
  BootNotification = "BootNotification",
  DiagnosticsStatusNotification = "DiagnosticsStatusNotification",
  FirmwareStatusNotification = "FirmwareStatusNotification",
  Heartbeat = "Heartbeat",
  MeterValues = "MeterValues",
  StatusNotification = "StatusNotification"
}
