/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TriggerMessageResponseV16 {
  status: TriggerMessageStatus;
}

export const enum TriggerMessageStatus {
  Accepted = "Accepted",
  Rejected = "Rejected",
  NotImplemented = "NotImplemented"
}
