/**
 * Generated by scripts/schema-ast.ts */
import authorizeResponseV201 from "./authorize-response.json";
import authorizeRequestV201 from "./authorize.json";
import bootNotificationResponseV201 from "./boot-notification-response.json";
import bootNotificationRequestV201 from "./boot-notification.json";
import cancelReservationResponseV201 from "./cancel-reservation-response.json";
import cancelReservationRequestV201 from "./cancel-reservation.json";
import certificateSignedResponseV201 from "./certificate-signed-response.json";
import certificateSignedRequestV201 from "./certificate-signed.json";
import changeAvailabilityResponseV201 from "./change-availability-response.json";
import changeAvailabilityRequestV201 from "./change-availability.json";
import clearCacheResponseV201 from "./clear-cache-response.json";
import clearCacheRequestV201 from "./clear-cache.json";
import clearChargingProfileResponseV201 from "./clear-charging-profile-response.json";
import clearChargingProfileRequestV201 from "./clear-charging-profile.json";
import clearDisplayMessageResponseV201 from "./clear-display-message-response.json";
import clearDisplayMessageRequestV201 from "./clear-display-message.json";
import clearVariableMonitoringResponseV201 from "./clear-variable-monitoring-response.json";
import clearVariableMonitoringRequestV201 from "./clear-variable-monitoring.json";
import clearedChargingLimitResponseV201 from "./cleared-charging-limit-response.json";
import clearedChargingLimitRequestV201 from "./cleared-charging-limit.json";
import costUpdatedResponseV201 from "./cost-updated-response.json";
import costUpdatedRequestV201 from "./cost-updated.json";
import customerInformationResponseV201 from "./customer-information-response.json";
import customerInformationRequestV201 from "./customer-information.json";
import dataTransferResponseV201 from "./data-transfer-response.json";
import dataTransferRequestV201 from "./data-transfer.json";
import deleteCertificateResponseV201 from "./delete-certificate-response.json";
import deleteCertificateRequestV201 from "./delete-certificate.json";
import firmwareStatusNotificationResponseV201 from "./firmware-status-notification-response.json";
import firmwareStatusNotificationRequestV201 from "./firmware-status-notification.json";
import getBaseReportResponseV201 from "./get-base-report-response.json";
import getBaseReportRequestV201 from "./get-base-report.json";
import getCertificateStatusResponseV201 from "./get-certificate-status-response.json";
import getCertificateStatusRequestV201 from "./get-certificate-status.json";
import getChargingProfilesResponseV201 from "./get-charging-profiles-response.json";
import getChargingProfilesRequestV201 from "./get-charging-profiles.json";
import getCompositeScheduleResponseV201 from "./get-composite-schedule-response.json";
import getCompositeScheduleRequestV201 from "./get-composite-schedule.json";
import getDisplayMessagesResponseV201 from "./get-display-messages-response.json";
import getDisplayMessagesRequestV201 from "./get-display-messages.json";
import getInstalledCertificateIdsResponseV201 from "./get-installed-certificate-ids-response.json";
import getInstalledCertificateIdsRequestV201 from "./get-installed-certificate-ids.json";
import getLocalListVersionResponseV201 from "./get-local-list-version-response.json";
import getLocalListVersionRequestV201 from "./get-local-list-version.json";
import getLogResponseV201 from "./get-log-response.json";
import getLogRequestV201 from "./get-log.json";
import getMonitoringReportResponseV201 from "./get-monitoring-report-response.json";
import getMonitoringReportRequestV201 from "./get-monitoring-report.json";
import getReportResponseV201 from "./get-report-response.json";
import getReportRequestV201 from "./get-report.json";
import getTransactionStatusResponseV201 from "./get-transaction-status-response.json";
import getTransactionStatusRequestV201 from "./get-transaction-status.json";
import getVariablesResponseV201 from "./get-variables-response.json";
import getVariablesRequestV201 from "./get-variables.json";
import get15118EVCertificateResponseV201 from "./get15118-e-v-certificate-response.json";
import get15118EVCertificateRequestV201 from "./get15118-e-v-certificate.json";
import heartbeatResponseV201 from "./heartbeat-response.json";
import heartbeatRequestV201 from "./heartbeat.json";
import installCertificateResponseV201 from "./install-certificate-response.json";
import installCertificateRequestV201 from "./install-certificate.json";
import logStatusNotificationResponseV201 from "./log-status-notification-response.json";
import logStatusNotificationRequestV201 from "./log-status-notification.json";
import meterValuesResponseV201 from "./meter-values-response.json";
import meterValuesRequestV201 from "./meter-values.json";
import notifyChargingLimitResponseV201 from "./notify-charging-limit-response.json";
import notifyChargingLimitRequestV201 from "./notify-charging-limit.json";
import notifyCustomerInformationResponseV201 from "./notify-customer-information-response.json";
import notifyCustomerInformationRequestV201 from "./notify-customer-information.json";
import notifyDisplayMessagesResponseV201 from "./notify-display-messages-response.json";
import notifyDisplayMessagesRequestV201 from "./notify-display-messages.json";
import notifyEVChargingNeedsResponseV201 from "./notify-e-v-charging-needs-response.json";
import notifyEVChargingNeedsRequestV201 from "./notify-e-v-charging-needs.json";
import notifyEVChargingScheduleResponseV201 from "./notify-e-v-charging-schedule-response.json";
import notifyEVChargingScheduleRequestV201 from "./notify-e-v-charging-schedule.json";
import notifyEventResponseV201 from "./notify-event-response.json";
import notifyEventRequestV201 from "./notify-event.json";
import notifyMonitoringReportResponseV201 from "./notify-monitoring-report-response.json";
import notifyMonitoringReportRequestV201 from "./notify-monitoring-report.json";
import notifyReportResponseV201 from "./notify-report-response.json";
import notifyReportRequestV201 from "./notify-report.json";
import publishFirmwareResponseV201 from "./publish-firmware-response.json";
import publishFirmwareStatusNotificationResponseV201 from "./publish-firmware-status-notification-response.json";
import publishFirmwareStatusNotificationRequestV201 from "./publish-firmware-status-notification.json";
import publishFirmwareRequestV201 from "./publish-firmware.json";
import reportChargingProfilesResponseV201 from "./report-charging-profiles-response.json";
import reportChargingProfilesRequestV201 from "./report-charging-profiles.json";
import reservationStatusUpdateResponseV201 from "./reservation-status-update-response.json";
import reservationStatusUpdateRequestV201 from "./reservation-status-update.json";
import reserveNowResponseV201 from "./reserve-now-response.json";
import reserveNowRequestV201 from "./reserve-now.json";
import resetResponseV201 from "./reset-response.json";
import resetRequestV201 from "./reset.json";
import rpcCallErrorV201 from "./rpc-call-error.json";
import rpcCallResultV201 from "./rpc-call-result.json";
import rpcCallV201 from "./rpc-call.json";
import securityEventNotificationResponseV201 from "./security-event-notification-response.json";
import securityEventNotificationRequestV201 from "./security-event-notification.json";
import sendLocalListResponseV201 from "./send-local-list-response.json";
import sendLocalListRequestV201 from "./send-local-list.json";
import setChargingProfileResponseV201 from "./set-charging-profile-response.json";
import setChargingProfileRequestV201 from "./set-charging-profile.json";
import setDisplayMessageResponseV201 from "./set-display-message-response.json";
import setDisplayMessageRequestV201 from "./set-display-message.json";
import setMonitoringBaseResponseV201 from "./set-monitoring-base-response.json";
import setMonitoringBaseRequestV201 from "./set-monitoring-base.json";
import setMonitoringLevelResponseV201 from "./set-monitoring-level-response.json";
import setMonitoringLevelRequestV201 from "./set-monitoring-level.json";
import setNetworkProfileResponseV201 from "./set-network-profile-response.json";
import setNetworkProfileRequestV201 from "./set-network-profile.json";
import setVariableMonitoringResponseV201 from "./set-variable-monitoring-response.json";
import setVariableMonitoringRequestV201 from "./set-variable-monitoring.json";
import setVariablesResponseV201 from "./set-variables-response.json";
import setVariablesRequestV201 from "./set-variables.json";
import signCertificateResponseV201 from "./sign-certificate-response.json";
import signCertificateRequestV201 from "./sign-certificate.json";
import requestStartTransactionResponseV201 from "./start-transaction-response.json";
import requestStartTransactionRequestV201 from "./start-transaction.json";
import statusNotificationResponseV201 from "./status-notification-response.json";
import statusNotificationRequestV201 from "./status-notification.json";
import requestStopTransactionResponseV201 from "./stop-transaction-response.json";
import requestStopTransactionRequestV201 from "./stop-transaction.json";
import transactionEventResponseV201 from "./transaction-event-response.json";
import transactionEventRequestV201 from "./transaction-event.json";
import triggerMessageResponseV201 from "./trigger-message-response.json";
import triggerMessageRequestV201 from "./trigger-message.json";
import unlockConnectorResponseV201 from "./unlock-connector-response.json";
import unlockConnectorRequestV201 from "./unlock-connector.json";
import unpublishFirmwareResponseV201 from "./unpublish-firmware-response.json";
import unpublishFirmwareRequestV201 from "./unpublish-firmware.json";
import updateFirmwareResponseV201 from "./update-firmware-response.json";
import updateFirmwareRequestV201 from "./update-firmware.json";

export const schemas = {
    v201: {
        authorizeResponseV201,
        authorizeRequestV201,
        bootNotificationResponseV201,
        bootNotificationRequestV201,
        cancelReservationResponseV201,
        cancelReservationRequestV201,
        certificateSignedResponseV201,
        certificateSignedRequestV201,
        changeAvailabilityResponseV201,
        changeAvailabilityRequestV201,
        clearCacheResponseV201,
        clearCacheRequestV201,
        clearChargingProfileResponseV201,
        clearChargingProfileRequestV201,
        clearDisplayMessageResponseV201,
        clearDisplayMessageRequestV201,
        clearVariableMonitoringResponseV201,
        clearVariableMonitoringRequestV201,
        clearedChargingLimitResponseV201,
        clearedChargingLimitRequestV201,
        costUpdatedResponseV201,
        costUpdatedRequestV201,
        customerInformationResponseV201,
        customerInformationRequestV201,
        dataTransferResponseV201,
        dataTransferRequestV201,
        deleteCertificateResponseV201,
        deleteCertificateRequestV201,
        firmwareStatusNotificationResponseV201,
        firmwareStatusNotificationRequestV201,
        getBaseReportResponseV201,
        getBaseReportRequestV201,
        getCertificateStatusResponseV201,
        getCertificateStatusRequestV201,
        getChargingProfilesResponseV201,
        getChargingProfilesRequestV201,
        getCompositeScheduleResponseV201,
        getCompositeScheduleRequestV201,
        getDisplayMessagesResponseV201,
        getDisplayMessagesRequestV201,
        getInstalledCertificateIdsResponseV201,
        getInstalledCertificateIdsRequestV201,
        getLocalListVersionResponseV201,
        getLocalListVersionRequestV201,
        getLogResponseV201,
        getLogRequestV201,
        getMonitoringReportResponseV201,
        getMonitoringReportRequestV201,
        getReportResponseV201,
        getReportRequestV201,
        getTransactionStatusResponseV201,
        getTransactionStatusRequestV201,
        getVariablesResponseV201,
        getVariablesRequestV201,
        get15118EVCertificateResponseV201,
        get15118EVCertificateRequestV201,
        heartbeatResponseV201,
        heartbeatRequestV201,
        installCertificateResponseV201,
        installCertificateRequestV201,
        logStatusNotificationResponseV201,
        logStatusNotificationRequestV201,
        meterValuesResponseV201,
        meterValuesRequestV201,
        notifyChargingLimitResponseV201,
        notifyChargingLimitRequestV201,
        notifyCustomerInformationResponseV201,
        notifyCustomerInformationRequestV201,
        notifyDisplayMessagesResponseV201,
        notifyDisplayMessagesRequestV201,
        notifyEVChargingNeedsResponseV201,
        notifyEVChargingNeedsRequestV201,
        notifyEVChargingScheduleResponseV201,
        notifyEVChargingScheduleRequestV201,
        notifyEventResponseV201,
        notifyEventRequestV201,
        notifyMonitoringReportResponseV201,
        notifyMonitoringReportRequestV201,
        notifyReportResponseV201,
        notifyReportRequestV201,
        publishFirmwareResponseV201,
        publishFirmwareStatusNotificationResponseV201,
        publishFirmwareStatusNotificationRequestV201,
        publishFirmwareRequestV201,
        reportChargingProfilesResponseV201,
        reportChargingProfilesRequestV201,
        reservationStatusUpdateResponseV201,
        reservationStatusUpdateRequestV201,
        reserveNowResponseV201,
        reserveNowRequestV201,
        resetResponseV201,
        resetRequestV201,
        rpcCallErrorV201,
        rpcCallResultV201,
        rpcCallV201,
        securityEventNotificationResponseV201,
        securityEventNotificationRequestV201,
        sendLocalListResponseV201,
        sendLocalListRequestV201,
        setChargingProfileResponseV201,
        setChargingProfileRequestV201,
        setDisplayMessageResponseV201,
        setDisplayMessageRequestV201,
        setMonitoringBaseResponseV201,
        setMonitoringBaseRequestV201,
        setMonitoringLevelResponseV201,
        setMonitoringLevelRequestV201,
        setNetworkProfileResponseV201,
        setNetworkProfileRequestV201,
        setVariableMonitoringResponseV201,
        setVariableMonitoringRequestV201,
        setVariablesResponseV201,
        setVariablesRequestV201,
        signCertificateResponseV201,
        signCertificateRequestV201,
        requestStartTransactionResponseV201,
        requestStartTransactionRequestV201,
        statusNotificationResponseV201,
        statusNotificationRequestV201,
        requestStopTransactionResponseV201,
        requestStopTransactionRequestV201,
        transactionEventResponseV201,
        transactionEventRequestV201,
        triggerMessageResponseV201,
        triggerMessageRequestV201,
        unlockConnectorResponseV201,
        unlockConnectorRequestV201,
        unpublishFirmwareResponseV201,
        unpublishFirmwareRequestV201,
        updateFirmwareResponseV201,
        updateFirmwareRequestV201
    }
};