name: Publish Package to npmjs
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: true
      - run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION=${TAG#v}
          echo "VERSION is: $VERSION"
          pnpm build
          pnpm publish --publish-branch main --no-git-checks --tag $VERSION
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
